name: repos
version: "0.2"

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.10
  - containers >= 0.5.10
  - dhall >= 1.11
  - insert-ordered-containers >= 0.2
  - optparse-applicative >= 0.13
  - system-filepath == 0.4.*
  - text >= 1.2
  - text-format >= 0.3
  - trifecta >= 1.7
  - turtle >= 1.3
  - unix == 2.7.*
  - vector >= 0.11

executables:
  repos:
    main: repos.hs
    other-modules:
      - Actions
      - Actions.Git
      - Actions.Helpers
      - Actions.Pass
      - Actions.Types
      - Actions.Vcsh
      - Config
      - Posix
