name: repos

dependencies:
  - base >= 4.7 && < 5
  - dhall == 1.2.*
  - optparse-applicative == 0.13.*
  - system-filepath == 0.4.*
  - text == 1.2.*
  - turtle == 1.3.*
  - unix == 2.7.*

executables:
  repos:
    main: repos.hs
    other-modules:
      - Actions
      - Actions.Git
      - Actions.Helpers
      - Actions.Types
      - Config
      - Posix
