name: repos

dependencies:
  - async
  - base >= 4.7 && < 5
  - bytestring >= 0.10
  - containers >= 0.5.10
  - dhall >= 1.12
  - directory
  - filepath
  - foldl
  - formatting
  - insert-ordered-containers >= 0.1
  - microlens-platform
  - mtl
  - optparse-applicative >= 0.13
  - pipes
  - pipes-bytestring
  - pipes-concurrency
  - pipes-parse
  - pipes-text
  - process
  - text >= 1.2
  - text-format >= 0.3
  - transformers
  - trifecta >= 1.7
  - turtle >= 1.3
  - unix == 2.7.*
  - vector >= 0.11

executables:
  repos:
    main: repos.hs
    other-modules:
      - Actions
      - Actions.Action
      - Actions.Command
      - Actions.Git
      - Actions.Helpers
      - Actions.Pass
      - Actions.Vcsh
      - Config
      - Posix
      - Process
