name: repos

dependencies:
  - base >= 4.7 && < 5
  - optparse-applicative >= 0.13
  - system-filepath == 0.4.*
  - text == 1.2.*
  - turtle >= 1.3
  - unix == 2.7.*
  - vector >= 0.11
  - yaml >= 0.8.23 && < 0.9

executables:
  repos:
    main: repos.hs
    other-modules:
      - Actions
      - Actions.Git
      - Actions.Helpers
      - Actions.Pass
      - Actions.Types
      - Actions.Vcsh
      - Config
      - Posix
